# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
   vmImage: 'ubuntu-latest'

variables:
   buildConfiguration: 'Release'
   TF_BUILD: 1

steps:
   - script: 'echo "##vso[build.updatebuildnumber]0.1.0-issue-gitversion.19"'
   - task: DotNetCoreCLI@2
     displayName: 'Build $(buildConfiguration)'
     inputs:
        command: build
        projects: '**/*.csproj'
        configuration: $(buildConfiguration)
        arguments: '--verbosity:n'
   - task: DotNetCoreCLI@2
     displayName: 'Publish'
     inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
   - task: PublishBuildArtifacts@1
     inputs:
        ArtifactName: $(System.TeamProject)-$(GitVersion.SemVer)
