version: '3'
services:
   db:
      image: 'mcr.microsoft.com/mssql/server:2019-latest'
      environment:
         SA_PASSWORD: 'singer-2019-password' # This is just for dev-purposes, so it doesn't matter if it is in config
         ACCEPT_EULA: 'Y'
      volumes:
         - ./.dev/sql/data:/var/opt/mssql/data
      ports:
         - 1433:1433

   smtp4dev:
      image: rnwood/smtp4dev:v3
      ports:
         - '3000:80'
         - '25:25'
