import { NgModule } from '@angular/core';

import {
   MatButtonModule,
   MatMenuModule,
   MatToolbarModule,
   MatIconModule,
   MatCardModule,
   MatListModule,
   MatTableModule,
   MatInputModule,
   MatPaginatorModule,
   MatSortModule,
   MatFormFieldModule,
   MatOptionModule,
   MatSelectModule,
   MatProgressSpinnerModule,
   MatDatepickerModule,
   MatDialogModule,
   MatDividerModule,
   MatGridListModule,
   MatChipsModule,
   MatTooltipModule,
   MatAutocompleteModule,
   MatButtonToggleModule,
   MatTabsModule,
   MatSnackBarModule,
   MatStepperModule,
} from '@angular/material';
import {
   MatMomentDateModule,
   MAT_MOMENT_DATE_ADAPTER_OPTIONS,
} from '@angular/material-moment-adapter';
import { NgxMaterialTimepickerModule } from 'ngx-material-timepicker';

@NgModule({
   imports: [
      MatButtonModule,
      MatInputModule,
      MatMenuModule,
      MatToolbarModule,
      MatIconModule,
      MatCardModule,
      MatListModule,
      MatTableModule,
      MatPaginatorModule,
      MatSortModule,
      MatFormFieldModule,
      MatOptionModule,
      MatSelectModule,
      MatProgressSpinnerModule,
      MatDatepickerModule,
      MatDialogModule,
      MatDividerModule,
      MatMomentDateModule,
      MatTooltipModule,
      NgxMaterialTimepickerModule,
      MatAutocompleteModule,
      MatSnackBarModule,
      MatTabsModule,
      MatSnackBarModule,
      MatButtonToggleModule,
      MatProgressSpinnerModule,
      MatStepperModule,
   ],
   exports: [
      MatButtonModule,
      MatInputModule,
      MatMenuModule,
      MatGridListModule,
      MatChipsModule,
      MatToolbarModule,
      MatIconModule,
      MatCardModule,
      MatListModule,
      MatTableModule,
      MatPaginatorModule,
      MatSortModule,
      MatFormFieldModule,
      MatOptionModule,
      MatSelectModule,
      MatProgressSpinnerModule,
      MatDatepickerModule,
      MatDialogModule,
      MatDividerModule,
      MatMomentDateModule,
      MatTooltipModule,
      NgxMaterialTimepickerModule,
      MatAutocompleteModule,
      MatButtonToggleModule,
      MatSnackBarModule,
      MatTabsModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatStepperModule,
   ],
   providers: [
      { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
   ],
})
export class MaterialModule {}
