//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Singer.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geaccepteerd.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volwassene.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsgroep.
        /// </summary>
        public static string AgeGroup {
            get {
                return ResourceManager.GetString("AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsgroepen.
        /// </summary>
        public static string AllowedAgeGroups {
            get {
                return ResourceManager.GetString("AllowedAgeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorggebruiker.
        /// </summary>
        public static string CareUser {
            get {
                return ResourceManager.GetString("CareUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id van de zorggebruiker.
        /// </summary>
        public static string CareUserId {
            get {
                return ResourceManager.GetString("CareUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorggebruikers.
        /// </summary>
        public static string CareUsers {
            get {
                return ResourceManager.GetString("CareUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toe te voegen zorggebruikers.
        /// </summary>
        public static string CareUsersToAdd {
            get {
                return ResourceManager.GetString("CareUsersToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te verwijderen zorggebruikers.
        /// </summary>
        public static string CareUsersToRemove {
            get {
                return ResourceManager.GetString("CareUsersToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossiernummer.
        /// </summary>
        public static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente/Stad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijs.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url van huidige pagina.
        /// </summary>
        public static string CurrentPageUrl {
            get {
                return ResourceManager.GetString("CurrentPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidig aantal inschrijvingen.
        /// </summary>
        public static string CurrentRegistrants {
            get {
                return ResourceManager.GetString("CurrentRegistrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start opvang na het evenement.
        /// </summary>
        public static string DayCareAfterEndDateTime {
            get {
                return ResourceManager.GetString("DayCareAfterEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start moment opvang voor het evenement.
        /// </summary>
        public static string DayCareBeforeStartDateTime {
            get {
                return ResourceManager.GetString("DayCareBeforeStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adres.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde moment.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eind moment registratie.
        /// </summary>
        public static string EndRegistrationDateTime {
            get {
                return ResourceManager.GetString("EndRegistrationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenement beschrijving.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id van het evenement.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenement slot.
        /// </summary>
        public static string EventSlot {
            get {
                return ResourceManager.GetString("EventSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id van het evenement slot.
        /// </summary>
        public static string EventSlotId {
            get {
                return ResourceManager.GetString("EventSlotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event slots.
        /// </summary>
        public static string EventSlots {
            get {
                return ResourceManager.GetString("EventSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uiterste annuleringsdatum.
        /// </summary>
        public static string FinalCancellationDateTime {
            get {
                return ResourceManager.GetString("FinalCancellationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvang na het evenement.
        /// </summary>
        public static string HasDayCareAfter {
            get {
                return ResourceManager.GetString("HasDayCareAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvang voor het evenement.
        /// </summary>
        public static string HasDayCareBefore {
            get {
                return ResourceManager.GetString("HasDayCareBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeft opvang normaal.
        /// </summary>
        public static string HasNormalDayCare {
            get {
                return ResourceManager.GetString("HasNormalDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traject.
        /// </summary>
        public static string HasTrajectory {
            get {
                return ResourceManager.GetString("HasTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeft vakantie opvang.
        /// </summary>
        public static string HasVacationDayCare {
            get {
                return ResourceManager.GetString("HasVacationDayCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval eenheid.
        /// </summary>
        public static string IntervalUnit {
            get {
                return ResourceManager.GetString("IntervalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klas/Extern.
        /// </summary>
        public static string IsExtern {
            get {
                return ResourceManager.GetString("IsExtern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleuter.
        /// </summary>
        public static string Kindergartener {
            get {
                return ResourceManager.GetString("Kindergartener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id van de voogd.
        /// </summary>
        public static string LegalGuardianId {
            get {
                return ResourceManager.GetString("LegalGuardianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voogden.
        /// </summary>
        public static string LegalGuardianUsers {
            get {
                return ResourceManager.GetString("LegalGuardianUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toe te voegen voogden.
        /// </summary>
        public static string LegalGuardianUsersToAdd {
            get {
                return ResourceManager.GetString("LegalGuardianUsersToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te verwijderen voogden.
        /// </summary>
        public static string LegalGuardianUsersToRemove {
            get {
                return ResourceManager.GetString("LegalGuardianUsersToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id van de locatie.
        /// </summary>
        public static string LocationId {
            get {
                return ResourceManager.GetString("LocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum aantal inschrijvingen.
        /// </summary>
        public static string MaxRegistrants {
            get {
                return ResourceManager.GetString("MaxRegistrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maand herhalingsmoment.
        /// </summary>
        public static string MonthRepeatMoment {
            get {
                return ResourceManager.GetString("MonthRepeatMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url naar volgende pagina.
        /// </summary>
        public static string NextPageUrl {
            get {
                return ResourceManager.GetString("NextPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvang normaal.
        /// </summary>
        public static string NormalDaycareLocation {
            get {
                return ResourceManager.GetString("NormalDaycareLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal herhalingen.
        /// </summary>
        public static string NumberOfRepeats {
            get {
                return ResourceManager.GetString("NumberOfRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina index.
        /// </summary>
        public static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te verwerken.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url naar vorige pagina.
        /// </summary>
        public static string PreviousPageUrl {
            get {
                return ResourceManager.GetString("PreviousPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registratie op dagelijkse basis.
        /// </summary>
        public static string RegistrationOnDailyBasis {
            get {
                return ResourceManager.GetString("RegistrationOnDailyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afgekeurd.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaling.
        /// </summary>
        public static string RepeatSettings {
            get {
                return ResourceManager.GetString("RepeatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhalingsmodus.
        /// </summary>
        public static string RepeatType {
            get {
                return ResourceManager.GetString("RepeatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grootte.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start moment.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start moment registratie.
        /// </summary>
        public static string StartRegistrationDateTime {
            get {
                return ResourceManager.GetString("StartRegistrationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop datum.
        /// </summary>
        public static string StopRepeatDate {
            get {
                return ResourceManager.GetString("StopRepeatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peuter.
        /// </summary>
        public static string Toddler {
            get {
                return ResourceManager.GetString("Toddler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal aantal.
        /// </summary>
        public static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvang vakantie.
        /// </summary>
        public static string VacationDaycareLocation {
            get {
                return ResourceManager.GetString("VacationDaycareLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week herhalingsmoment.
        /// </summary>
        public static string WeekRepeatMoment {
            get {
                return ResourceManager.GetString("WeekRepeatMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jongere.
        /// </summary>
        public static string Youngster {
            get {
                return ResourceManager.GetString("Youngster", resourceCulture);
            }
        }
    }
}
