//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singer.Resources
{
   using System;


   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
   [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
   [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
   public class ErrorMessages
   {

      private static global::System.Resources.ResourceManager resourceMan;

      private static global::System.Globalization.CultureInfo resourceCulture;

      [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
      internal ErrorMessages()
      {
      }

      /// <summary>
      ///   Returns the cached ResourceManager instance used by this class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      public static global::System.Resources.ResourceManager ResourceManager
      {
         get
         {
            if (object.ReferenceEquals(resourceMan, null))
            {
               global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Singer.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
               resourceMan = temp;
            }
            return resourceMan;
         }
      }

      /// <summary>
      ///   Overrides the current thread's CurrentUICulture property for all
      ///   resource lookups using this strongly typed resource class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      public static global::System.Globalization.CultureInfo Culture
      {
         get
         {
            return resourceCulture;
         }
         set
         {
            resourceCulture = value;
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De gegeven data kon niet verwerkt worden op de server..
      /// </summary>
      public static string BadInputError
      {
         get
         {
            return ResourceManager.GetString("BadInputError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De geboortedatum van de zorggebruiker kan niet na vandaag vallen..
      /// </summary>
      public static string BirthDayInTheFuture
      {
         get
         {
            return ResourceManager.GetString("BirthDayInTheFuture", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De start tijd/datum om te registreren kan liggen na de start tijd/datum van het evenement..
      /// </summary>
      public static string CannotRegistrateAfterStartEvent
      {
         get
         {
            return ResourceManager.GetString("CannotRegistrateAfterStartEvent", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De opvang na het evenement kan niet starten als het evenement nog bezig is..
      /// </summary>
      public static string CannotStartDaycareAfterWhileEventIsBusy
      {
         get
         {
            return ResourceManager.GetString("CannotStartDaycareAfterWhileEventIsBusy", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De opvang vóór het evenement kan niet starten als het evenement al bezig is..
      /// </summary>
      public static string CannotStartDaycareBeforeWhenEventIsBusy
      {
         get
         {
            return ResourceManager.GetString("CannotStartDaycareBeforeWhenEventIsBusy", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De start tijd/datum kan niet na het einde gebeuren..
      /// </summary>
      public static string CannotStartEventAfterEndingIt
      {
         get
         {
            return ResourceManager.GetString("CannotStartEventAfterEndingIt", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De zorggebruiker bestaat niet..
      /// </summary>
      public static string CareUserDoesntExist
      {
         get
         {
            return ResourceManager.GetString("CareUserDoesntExist", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De zorggebruiker en voogd zijn al gekoppeld..
      /// </summary>
      public static string DuplicateCareUserLGUserLink
      {
         get
         {
            return ResourceManager.GetString("DuplicateCareUserLGUserLink", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Het email adres dat je opgaf bestaat reeds in de database..
      /// </summary>
      public static string DuplicateEmail
      {
         get
         {
            return ResourceManager.GetString("DuplicateEmail", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Het event id klopt niet..
      /// </summary>
      public static string EventIdMismatchUrlBody
      {
         get
         {
            return ResourceManager.GetString("EventIdMismatchUrlBody", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Het event slot kon niet gevonden worden..
      /// </summary>
      public static string EventSlotNotFound
      {
         get
         {
            return ResourceManager.GetString("EventSlotNotFound", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} is een verplicht veld..
      /// </summary>
      public static string FieldIsRequired
      {
         get
         {
            return ResourceManager.GetString("FieldIsRequired", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} mag maximaal {1} karakters bevatten..
      /// </summary>
      public static string FieldLengthCanMaximumBe
      {
         get
         {
            return ResourceManager.GetString("FieldLengthCanMaximumBe", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} moet een lengte hebben van minstens {2} en maximum {1} karakters..
      /// </summary>
      public static string FieldLengthMustBeBetween
      {
         get
         {
            return ResourceManager.GetString("FieldLengthMustBeBetween", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} moet tussen {1} en {2} zijn..
      /// </summary>
      public static string FieldMustBeBetween
      {
         get
         {
            return ResourceManager.GetString("FieldMustBeBetween", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} moet een lengte hebben van {2} karakters..
      /// </summary>
      public static string FieldMustHaveChars
      {
         get
         {
            return ResourceManager.GetString("FieldMustHaveChars", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You shall not pass!!!.
      /// </summary>
      public static string ForbiddenError
      {
         get
         {
            return ResourceManager.GetString("ForbiddenError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sorry er is iets misgegaan. Het aapje dat deze pagina hoort terug te geven is ontsnapt...
      ///We zijn bezig met hem terug te zoeken..
      /// </summary>
      public static string InternalServerError
      {
         get
         {
            return ResourceManager.GetString("InternalServerError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Het email address is niet geldig..
      /// </summary>
      public static string InvalidEmail
      {
         get
         {
            return ResourceManager.GetString("InvalidEmail", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De url is niet geldig.
      /// </summary>
      public static string InvalidUrl
      {
         get
         {
            return ResourceManager.GetString("InvalidUrl", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De voogd bestaat niet..
      /// </summary>
      public static string LegalGuardianDoesntExist
      {
         get
         {
            return ResourceManager.GetString("LegalGuardianDoesntExist", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De voogd en zorggebruiker zijn niet gekoppeld..
      /// </summary>
      public static string LinkCareUserLGUserDoesntExist
      {
         get
         {
            return ResourceManager.GetString("LinkCareUserLGUserDoesntExist", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Er is geen data meegegeven naar de server..
      /// </summary>
      public static string NoDataPassed
      {
         get
         {
            return ResourceManager.GetString("NoDataPassed", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to These are not the droids you&apos;re looking for....
      /// </summary>
      public static string NotFoundError
      {
         get
         {
            return ResourceManager.GetString("NotFoundError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De paginagrootte moet minstens 1 zijn..
      /// </summary>
      public static string PageSizeLessThanOne
      {
         get
         {
            return ResourceManager.GetString("PageSizeLessThanOne", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De start tijd/datum om te registreren kan niet na de eind registratie datum liggen..
      /// </summary>
      public static string StartCannotBeforEndRegistrationEvent
      {
         get
         {
            return ResourceManager.GetString("StartCannotBeforEndRegistrationEvent", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De start tijd/datum voor de opvang na het evenement moet nog worden ingevuld..
      /// </summary>
      public static string StartDaycareAfterNotEntered
      {
         get
         {
            return ResourceManager.GetString("StartDaycareAfterNotEntered", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to De start tijd/datum voor de opvang vóór het evenement moet nog worden ingevuld..
      /// </summary>
      public static string StartDaycareBeforeNotEntered
      {
         get
         {
            return ResourceManager.GetString("StartDaycareBeforeNotEntered", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to One does not simply make a request to this API and gets all the data..
      /// </summary>
      public static string UnauthorizedError
      {
         get
         {
            return ResourceManager.GetString("UnauthorizedError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sorry, er is een fout gebeurd op de server die niet juist werd afgehandeld..
      /// </summary>
      public static string UnhandledServerError
      {
         get
         {
            return ResourceManager.GetString("UnhandledServerError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Ongekende sorteer opdracht voor de server..
      /// </summary>
      public static string UnknownSortDirection
      {
         get
         {
            return ResourceManager.GetString("UnknownSortDirection", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Deze gebruiker is reeds geregistreerd op dit tijdslot!.
      /// </summary>
      public static string UserAlreadyRegisteredOnEventSlot
      {
         get
         {
            return ResourceManager.GetString("UserAlreadyRegisteredOnEventSlot", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Er is geen gebruiker gevonden met het opgegeven ID..
      /// </summary>
      public static string UserNotFoundError
      {
         get
         {
            return ResourceManager.GetString("UserNotFoundError", resourceCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Het is niet toegestaan om de laatste beheerder te verwijderen, er moet minimaal 1 beheerder geconfigureerd blijven.
      /// </summary>
      public static string LastAdminUser
      {
         get
         {
            return ResourceManager.GetString("LastAdminUser", resourceCulture);
         }
      }
   }
}
