using System;
using System.Collections.Generic;
using System.Linq;
using Singer.DTOs;
using Singer.Models;

namespace Singer.DummyDataSeeder
{
    /// <summary>Static class that generates random numbers.</summary>
    public class Randomizer
    {
        private static Randomizer instance;

        /// <summary>Singleton instance of a <see cref="Randomizer"/>.</summary>
        public static Randomizer Instance => instance ??= new Randomizer();

        private static Random random;

        /// <summary>Internal <see cref="System.Random"/> instance.</summary>
        /// <remarks>
        ///     Why 163?
        ///     <para>
        ///         It is the largest value of d such that the number field ℚ⁢(-d) has class number
        ///         1, meaning that its ring of integers is a unique factorization domain. The issue
        ///         of factorization in quadratic fields, and of number fields in general, is one of
        ///         the principal driving forces of algebraic number theory, and to be able to
        ///         pinpoint the end of perfect factorization in the quadratic case like this seems
        ///         at least arguably fundamental.
        ///     </para>
        ///     <para>
        ///         But even if you don’t care about factorization in number fields, the above fact
        ///         has some amazing repercussions to more basic number theory. The two following
        ///         facts in particular jump out:
        ///     </para>
        ///     <list type="bullet">
        ///         <item>eπ⁢163 is within 10-12 of an integer.</item>
        ///         <item>
        ///             The polynomial f⁢(x)=x2+x+41 has the property that for integers 1≤x≤41,
        ///             f⁢(x) is prime.
        ///         </item>
        ///     </list>
        ///     <para>
        ///         Both of these are tied intimately (the former using deep properties of the
        ///         j-function, the latter using relatively simple arguments concerning the
        ///         splitting of primes in number fields) to the above quadratic imaginary number
        ///         field having class number 1. Further, since ℚ⁢(-d) is the last such field, the
        ///         two listed properties are in some sense the best possible.
        ///     </para>
        ///     <para>
        ///         Most striking to me, however, is the amazing frequency with which 163 shows up
        ///         in a wide variety of class number problems. In addition to being the last value
        ///         of d such that ℚ⁢(-d) has class number 1, it is the first value of p such that
        ///         ℚ⁢(ζp+ζp-1) (the maximal real subfield of the p-th cyclotomic field) has class
        ///         number greater than 1. That 163 appears as the last instance of a quadratic
        ///         field having unique factorization, and the first instance of a real cyclotomic
        ///         field not having unique factorization, seems too remarkable to be coincidental.
        ///         This is (maybe) further substantiated by a couple of other factoids
        ///     </para>
        ///     <list type="bullet">
        ///         <item>
        ///             Hasse asked for an example of a prime and an extension such that the prime
        ///             splits completely into divisors which do not lie in a cyclic subgroup of the
        ///             class group. The first such example is any prime less than 163 which splits
        ///             completely in the cubic field generated by the polynomial x3=11⁢x2+14⁢x+1.
        ///             This field has discriminant 1632. (See Shanks’ The Simplest Cubic Fields).
        ///         </item>
        ///         <item>
        ///             The maximal conductor if an imaginary abelian number field of class number 1
        ///             corresponds to the field ℚ⁢(-67,-163), which has conductor 10921=67*163.
        ///         </item>
        ///     </list>
        ///     <para>
        ///         t is unclear whether or not these additional arithmetical properties reflect
        ///         deeper properties of the j-function or other modular forms, and remains a wide
        ///         open field of study.
        ///     </para>
        /// </remarks>
        public static Random Random => random ??= new Random(163);

        public string NewCaseNumber()
        {
            const string AllowedChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var length = Random.Next(7, 10);
            var chars = Enumerable.Repeat("", length)
                .Select(_ => AllowedChars[Random.Next(AllowedChars.Length)])
                .ToArray();

            return new string(chars);
        }

        public bool NewBool() => Random.NextDouble() > 0.5;

        public DateTime NewDateTime(DateTime min, DateTime max)
        {
            var d = random.NextDouble();
            var diff = max.Ticks - min.Ticks;

            // if d == 0 => new DateTime = min
            // if d == 1 => new DateTime = max
            // if d == 0.5 => new DateTime = min + max * 0.5

            var add = diff * d;
            return min.AddTicks((long)add);
        }

        public T Pick<T>(IList<T> items)
        {
            var i = Random.Next(0, items.Count);
            return items[i];
        }
    }
}
